In [1]:
import pandas as pd

tips = pd.read_csv("https://milliams.com/courses/data_analysis_python/tips.csv")

In [2]:
tips[tips["size"] >= 5]

     total_bill   tip   day    time  size
125       29.80  2.94  Thur   Lunch     6
141       34.30  4.69  Thur   Lunch     6
142       41.19  3.50  Thur   Lunch     5
143       27.05  3.50  Thur   Lunch     6
155       29.85  3.60   Sun  Dinner     5
156       48.17  3.50   Sun  Dinner     6
185       20.69  3.50   Sun  Dinner     5
187       30.46  1.40   Sun  Dinner     5
216       28.15  2.10   Sat  Dinner     5